---

- name: Converge
  hosts: grp_targets
  vars:
    no_prompts: true  # mariadb prompts

    semaphore:
      persistent_requirements: true
      requirements:
        pip: ['httpx']
        collections: ['ansible.utils', 'community.crypto', 'community.general']
        roles: ['ansibleguy.infra_nftables']
      nginx:
        domain: 'semaphore.test.ansibleguy.net'
      admin:
        user: 'admin'
        name: 'AnsibleGuy'
        email: 'semaphore@test.ansibleguy.net'

  roles:
    - ansibleguy.sw_semaphore
