---

- name: Verify
  hosts: grp_tester
  gather_facts: false
  tasks:
    - name: Checking if semaphore web-service is reachable
      ansible.builtin.uri:
        url: 'https://192.168.15.2'
        return_content: yes
        validate_certs: false
      register: page
      failed_when: "'Ansible Semaphore' not in page.content"
