---

- name: Semaphore | Backup | Service & Timer
  ansible.builtin.template:
    src: "templates/etc/systemd/system/{{ SEM_HC.service_backup }}.{{ item }}.j2"
    dest: "/etc/systemd/system/{{ SEM_HC.service_backup }}.{{ item }}"
    mode: 0644
  loop: ['service', 'timer']

- name: Semaphore | Backup | Enabling Backup
  ansible.builtin.systemd:
    name: "{{ SEM_HC.service_backup }}.timer"
    enabled: true
    state: started
    daemon_reload: true
