---

- name: Semaphore | Persistent-Requirements | Installing ansible-collections
  ansible.builtin.shell: "source {{ SEM_CONFIG.path.venv }}/bin/activate &&
  ansible-galaxy collection install {{ item }}"
  args:
    executable: '/bin/bash'
  register: sem_req_col
  changed_when: "'was installed' in sem_req_col.stdout"
  loop: "{{ SEM_CONFIG.requirements.collections }}"

- name: Semaphore | Persistent-Requirements | Installing ansible-roles
  ansible.builtin.shell: "source {{ SEM_CONFIG.path.venv }}/bin/activate &&
  ansible-galaxy install {{ item }}"
  args:
    executable: '/bin/bash'
  register: sem_req_role
  changed_when: "'was installed' in sem_req_role.stdout"
  loop: "{{ SEM_CONFIG.requirements.roles }}"

- name: Semaphore | Persistent-Requirements | Update-service
  ansible.builtin.template:
    src: "templates/etc/systemd/system/{{ SEM_HC.service_req }}.{{ item }}.j2"
    dest: "/etc/systemd/system/{{ SEM_HC.service_req }}.{{ item }}"
    mode: 0644
  loop: ['service', 'timer']

- name: Semaphore | Persistent-Requirements | Enabling Updater
  ansible.builtin.systemd:
    name: "{{ SEM_HC.service_req }}.timer"
    enabled: true
    state: started
    daemon_reload: true
